### ISSUE TITLE
Is there a way to keep the aspect ration of the crop box?

### ISSUE THREAD

**Issue by bitdelve** [pikachu987/CropPickerView#5]
I want to ensure that the image crop is square only, then I plan to resize the cropped image to something like 150x150. Is there a way to do this?

**Comment by krishnilbhojani** [comment]
@bitdelve have you found the answer for this?

**Comment by sohan-pixster** [comment]
give me ans if u found !

**Comment by pikachu987** [comment]
You can use the isSquare property from version '0.2.8'.
isSquare is false by default. If true, the top, left, bottom, and right buttons are hidden, and dragging leftTop, leftBottom, rightTop, and rightBottom changes the size in a 1:1 ratio.
