### ISSUE TITLE
Resize in Aspect ratio

### ISSUE THREAD

**Issue by SanjayRathor** [pikachu987/CropPickerView#8]
Hi,
 It is wonderful lib but can this supports resizing with the aspect ratio. like 4:3 or 3:4

**Comment by pikachu987** [comment]
Thanks for the additional comments.
Version 0.3.0 has been released. 🎉

isSquare, which expresses a square, has been replaced with AspectRatio.
Added AspectRatio property.
AspectRatio defines the aspect ratio.
AspectRatio is in the form of a CGFloat and means horizontal: vertical.
E.g
If width:height = 1:2
aspectRatio = 1/2.

Have a nice day 👍

**Comment by SanjayRathor** [comment]
Thanks  a lot .


Sanjay Singh Rathor
